### ISSUE TITLE
run button not working

### ISSUE THREAD

**Issue by bbodenmiller** [jonagh/gapi-querier#3]
As far as I can tell I have everything setup correctly and I've signed in but run command isn't working no produces any errors in console or network activity.

![image](https://user-images.githubusercontent.com/1192780/58746465-5d88c400-8413-11e9-938f-8b7998020b7d.png)

**Comment by jonagh** [comment]
It appears you didn't sign in successfully (as per the "error:[object Object]".

Admittedly that error isn't very helpful.. so I just pushed a change to the code that will display the error object/message details instead of just [object Object]. Hopefully that helps, let me know.

**Comment by bbodenmiller** [comment]
And now it's working. 🤷
